# Generated by Django 4.2 on 2023-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0002_alter_urls_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='ids',
            field=models.TextField(default='asdf', unique=True, verbose_name='ids'),
        ),
    ]
