# Generated by Django 4.2 on 2023-05-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0003_urls_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='ids',
            field=models.TextField(unique=True, verbose_name='ids'),
        ),
    ]
